#!/usr/bin/env bash
#
# build-installer.sh — regenerate scripts/install-ai-workflow-kit.sh from the
# current files in .claude/commands, .claude/skills, and scripts.
#
# Run from the repo root. The output is a self-contained installer users can
# run in their own project root.

set -euo pipefail

out="scripts/install-ai-workflow-kit.sh"
tmp="$(mktemp)"

emit_file() {
  local src="$1"
  local dst="$2"
  printf '\ncat > %s <<'\''AIWK_EOF'\''\n' "$dst" >> "$tmp"
  cat "$src" >> "$tmp"
  printf 'AIWK_EOF\n' >> "$tmp"
}

{
  cat <<'HEADER'
#!/usr/bin/env bash
#
# AI Workflow Kit installer (spcrd prefix edition)
# Auto-generated by scripts/build-installer.sh — do not edit by hand.
#
# Installs into the current working directory:
#   - .claude/commands/spcrd-*.md                        (9 slash commands)
#   - .claude/skills/project-development-workflow/SKILL.md
#   - scripts/check-crg-evidence.sh
#   - scripts/check-openspec-gate.sh
#   - scripts/detect-change-id.sh
#   - scripts/verify-install.sh

set -euo pipefail

mkdir -p .claude/commands
mkdir -p .claude/skills/project-development-workflow
mkdir -p scripts

HEADER
} > "$tmp"

for cmd in \
  spcrd-start spcrd-plan spcrd-dev spcrd-review spcrd-archive \
  spcrd-bugfix spcrd-hotfix spcrd-refactor spcrd-audit
do
  emit_file ".claude/commands/${cmd}.md" ".claude/commands/${cmd}.md"
done

emit_file ".claude/skills/project-development-workflow/SKILL.md" \
          ".claude/skills/project-development-workflow/SKILL.md"

emit_file "scripts/check-crg-evidence.sh"   "scripts/check-crg-evidence.sh"
emit_file "scripts/check-openspec-gate.sh"  "scripts/check-openspec-gate.sh"
emit_file "scripts/detect-change-id.sh"     "scripts/detect-change-id.sh"
emit_file "scripts/verify-install.sh"       "scripts/verify-install.sh"

cat >> "$tmp" <<'FOOTER'

chmod +x scripts/check-crg-evidence.sh
chmod +x scripts/check-openspec-gate.sh
chmod +x scripts/detect-change-id.sh
chmod +x scripts/verify-install.sh

echo ""
echo "AI Workflow Kit installed."
echo ""
echo "Verifying installation..."
if scripts/verify-install.sh .; then
  echo ""
  echo "Next:"
  echo "  1. Append the Project AI Workflow Kit section to your CLAUDE.md"
  echo "  2. Ensure OpenSpec, Superpowers, and code-review-graph are set up"
  echo "  3. Try: /spcrd-start <description>"
else
  echo ""
  echo "Installation finished but acceptance checks failed — see output above."
  exit 1
fi
FOOTER

mv "$tmp" "$out"
chmod +x "$out"
echo "Wrote $out ($(wc -l < "$out") lines)"
