#!/usr/bin/env bash
#
# AI Workflow Kit installer (spcrg prefix edition)
# Auto-generated by scripts/build-installer.sh — do not edit by hand.
#
# Installs into the current working directory:
#   - .claude/commands/spcrg-*.md                        (9 slash commands)
#   - .claude/skills/project-development-workflow/SKILL.md
#   - scripts/check-crg-evidence.sh
#   - scripts/check-openspec-gate.sh
#   - scripts/detect-change-id.sh
#   - scripts/verify-install.sh

set -euo pipefail

mkdir -p .claude/commands
mkdir -p .claude/skills/project-development-workflow
mkdir -p scripts


cat > .claude/commands/spcrg-start.md <<'AIWK_EOF'
# Spcrg Start: OpenSpec OPSX + Superpowers + CRG

User input:

$ARGUMENTS

Start a new feature or significant change using the mandatory project workflow.

## Steps

1. Run OpenSpec propose:

/opsx:propose $ARGUMENTS

2. Do not implement code.

3. After OpenSpec artifacts are created, identify the change-id and verify these files exist:

- openspec/changes/{change-id}/proposal.md
- openspec/changes/{change-id}/design.md
- openspec/changes/{change-id}/specs/**
- openspec/changes/{change-id}/tasks.md

4. Run CRG Context Pass.

Required CRG tools:

- build_or_update_graph_tool if graph is missing or stale
- list_graph_stats_tool
- get_minimal_context_tool
- get_architecture_overview_tool
- list_communities_tool
- get_community_tool for relevant communities
- semantic_search_nodes_tool
- query_graph_tool for callers/callees/imports/tests_for
- get_impact_radius_tool if target files/modules are known

If the change is cross-module, architecture-sensitive, permission-related, data-model-related, or core-flow-related, also use:

- get_hub_nodes_tool
- get_bridge_nodes_tool
- get_knowledge_gaps_tool
- get_surprising_connections_tool
- get_suggested_questions_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server and record the exact names used inside CRG Evidence.

5. Write CRG Evidence into:

- proposal.md → CRG Architecture Context
- design.md → CRG Impact Analysis

6. Use superpowers:brainstorming.

Inputs:

- proposal.md
- design.md
- specs/**
- tasks.md
- CRG Evidence

Brainstorm must clarify:

- requirement boundaries
- technical approach
- scope / out of scope
- measurable success criteria
- feature flag / migration / compatibility needs
- testing and E2E strategy
- CRG-discovered risks
- whether this should be split into multiple OpenSpec changes

7. Update:

- proposal.md
- design.md
- specs/**
- tasks.md

8. If brainstorming changes target modules, API boundaries, data models, permissions, testing strategy, E2E scope, or task split, run CRG Recheck using:

- semantic_search_nodes_tool
- query_graph_tool callers/callees/imports/tests_for
- get_impact_radius_tool
- list_communities_tool / get_community_tool when target modules changed
- get_hub_nodes_tool / get_bridge_nodes_tool / get_surprising_connections_tool / get_knowledge_gaps_tool for architecture or cross-module changes

## Gate: before requesting approval

Only after propose + CRG Context Pass + brainstorming + writing all artifacts + CRG Recheck are complete, run:

```
scripts/check-openspec-gate.sh <change-id>
scripts/check-crg-evidence.sh <change-id>
```

If either command fails:

1. Do not tell the user you are "waiting for approval".
2. Do not implement code.
3. Identify what is missing (OpenSpec artifact section or CRG Evidence).
4. Repair the missing content using the existing proposal / design / CRG tool outputs — do not expand scope.
5. Re-run both scripts.
6. Only when both scripts pass, continue.

After both scripts pass:

9. Stop and ask for human approval.

Do not implement code.

Stop if CRG is unavailable, stale, or fails.
AIWK_EOF

cat > .claude/commands/spcrg-plan.md <<'AIWK_EOF'
# Spcrg Plan

Change ID:

$ARGUMENTS

## Resolve change-id if missing

If `$ARGUMENTS` is empty:

1. Run `scripts/detect-change-id.sh`.
2. If exactly one active change exists, report it and ask the user to confirm before using it.
3. If multiple active changes exist, list them and ask the user to pick one.
4. If none exist, tell the user to run `/spcrg-start <description>` or `/opsx:propose <description>` first, then stop.

Do not proceed until a concrete change-id is chosen.

## Gate: before planning

Before writing the plan, run:

```
scripts/check-openspec-gate.sh $ARGUMENTS
scripts/check-crg-evidence.sh $ARGUMENTS
```

If either command fails:

1. Do not run `superpowers:writing-plans`.
2. Report exactly what is missing.
3. If the missing item can be fixed from existing context, fix the OpenSpec artifact or CRG Evidence first.
4. Re-run the failed script.
5. Continue only after both scripts pass.

## Plan phase

Use `superpowers:writing-plans` to rewrite the OpenSpec tasks file.

### Input files

- openspec/changes/$ARGUMENTS/proposal.md
- openspec/changes/$ARGUMENTS/design.md
- openspec/changes/$ARGUMENTS/specs/**
- openspec/changes/$ARGUMENTS/tasks.md

### CRG Planning Analysis

Before writing the plan, run these CRG tools:

Required:

- get_minimal_context_tool
- semantic_search_nodes_tool
- query_graph_tool for callers/callees/imports/tests_for
- get_impact_radius_tool

For complex flows, also use:

- traverse_graph_tool
- list_flows_tool
- get_flow_tool
- find_large_functions_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server and record the exact names used inside CRG Evidence.

### Output

Rewrite:

openspec/changes/$ARGUMENTS/tasks.md

Requirements:

1. Preserve OpenSpec checklist format.
2. Every task must include:
   - task id
   - exact files
   - TDD steps
   - verification command
   - related spec/design reference
   - related CRG evidence
3. Every phase must include:
   - CRG Pre-Phase Check
   - Tasks
   - CRG Post-Phase Check
4. Do not expand scope beyond OpenSpec.
5. Stop after writing the plan and ask for execution approval.

If CRG evidence is missing, run CRG first.
AIWK_EOF

cat > .claude/commands/spcrg-dev.md <<'AIWK_EOF'
# Spcrg Development

Change ID:

$ARGUMENTS

## Resolve change-id if missing

If `$ARGUMENTS` is empty:

1. Run `scripts/detect-change-id.sh`.
2. If exactly one active change exists, report it and ask the user to confirm before using it.
3. If multiple active changes exist, list them and ask the user to pick one.
4. If none exist, tell the user to run `/spcrg-start <description>` first, then stop.

Do not proceed until a concrete change-id is chosen.

## Gate: before development

Before starting implementation, run:

```
scripts/check-openspec-gate.sh $ARGUMENTS
scripts/check-crg-evidence.sh $ARGUMENTS
```

If either command fails:

1. Do not run `superpowers:subagent-driven-development`.
2. Do not edit code.
3. Report missing OpenSpec artifacts or missing CRG Evidence.
4. Fix missing evidence only if it can be produced safely from CRG tools.
5. Re-run scripts.
6. Continue only after both scripts pass.

## Development phase

Use `superpowers:subagent-driven-development`.

### Strict rules

1. Only execute tasks from:

openspec/changes/$ARGUMENTS/tasks.md

2. Every task must follow superpowers:test-driven-development:

- write failing test
- confirm red
- implement minimal code
- confirm green
- refactor

3. Before every phase, run CRG Pre-Phase Check.

Required CRG tools before phase:

- query_graph_tool for callers/callees/imports/tests_for
- semantic_search_nodes_tool
- get_impact_radius_tool

If the phase touches a user/business flow, also use:

- list_flows_tool
- get_flow_tool

If the phase touches complex code, also use:

- traverse_graph_tool
- find_large_functions_tool

4. After every phase, run CRG Post-Phase Check.

Required CRG tools after phase:

- detect_changes_tool
- get_impact_radius_tool
- get_affected_flows_tool
- query_graph_tool pattern="tests_for"

If unexpected impact appears, also use:

- get_review_context_tool
- get_surprising_connections_tool
- get_knowledge_gaps_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server and record the exact names used inside CRG Evidence.

5. Update tasks.md after each task/phase.

6. Stop immediately if:

- unexpected blast radius appears
- spec mismatch appears
- CRG unavailable
- test strategy missing
- subagent needs to exceed scope
AIWK_EOF

cat > .claude/commands/spcrg-review.md <<'AIWK_EOF'
# Spcrg Review

Change ID:

$ARGUMENTS

## Resolve change-id if missing

If `$ARGUMENTS` is empty:

1. Run `scripts/detect-change-id.sh`.
2. If exactly one active change exists, report it and ask the user to confirm before using it.
3. If multiple active changes exist, list them and ask the user to pick one.
4. If none exist, tell the user to run `/spcrg-start <description>` first, then stop.

Do not proceed until a concrete change-id is chosen.

## Gate: before review

Before final review, run:

```
scripts/check-openspec-gate.sh $ARGUMENTS
scripts/check-crg-evidence.sh $ARGUMENTS
```

If either command fails:

1. Do not perform final review yet.
2. Report missing artifacts/evidence.
3. Ask whether to repair evidence or return to the previous phase.
4. Continue only after both scripts pass.

## Review phases

Run final review for this OpenSpec change.

### Phase 1: OpenSpec Compliance Review

Check:

- proposal.md
- design.md
- specs/**
- tasks.md
- GIVEN/WHEN/THEN scenarios
- scope / out of scope
- success criteria

### Phase 2: CRG Final Impact Review

Required CRG tools:

- detect_changes_tool
- get_review_context_tool
- get_impact_radius_tool
- get_affected_flows_tool
- query_graph_tool pattern="tests_for"
- get_knowledge_gaps_tool

If architecture-sensitive, also use:

- get_surprising_connections_tool
- get_hub_nodes_tool
- get_bridge_nodes_tool
- get_suggested_questions_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server and record the exact names used inside CRG Evidence.

### Phase 3: Superpowers Review

Use:

superpowers:requesting-code-review

Check:

- TDD compliance
- minimal implementation
- YAGNI
- DRY
- complexity
- unverified claims
- test evidence

## Output

- blocking issues
- non-blocking issues
- missing tests
- CRG risk summary
- archive readiness recommendation

Do not archive.
AIWK_EOF

cat > .claude/commands/spcrg-archive.md <<'AIWK_EOF'
# Spcrg Archive

Change ID:

$ARGUMENTS

## Resolve change-id if missing

If `$ARGUMENTS` is empty:

1. Run `scripts/detect-change-id.sh`.
2. If exactly one active change exists, report it and ask the user to confirm before using it.
3. If multiple active changes exist, list them and ask the user to pick one.
4. If none exist, tell the user there is nothing to archive and stop.

Do not proceed until a concrete change-id is chosen.

## Gate: before archive

Before verification or archive, run:

```
scripts/check-openspec-gate.sh $ARGUMENTS
scripts/check-crg-evidence.sh $ARGUMENTS
```

If either command fails:

1. Do not run `/opsx:verify`.
2. Do not run `/opsx:archive`.
3. Report missing artifacts/evidence.
4. Continue only after both scripts pass.

After both scripts pass:

1. Run `superpowers:verification-before-completion`.
2. Run CRG Archive Gate (see below).
3. Re-run both gate scripts one more time right before `/opsx:verify`.
4. Run `/opsx:verify $ARGUMENTS`.
5. Only if verification passes, run `/opsx:archive $ARGUMENTS`.

## Run project checks

- unit tests
- integration tests
- E2E if applicable
- lint
- typecheck
- build

## CRG Archive Gate

Before `/opsx:verify`, run:

- detect_changes_tool
- get_review_context_tool
- get_impact_radius_tool
- get_affected_flows_tool
- get_knowledge_gaps_tool

If user flow is affected, also use:

- list_flows_tool
- get_flow_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server and record the exact names used inside CRG Evidence.

## Report

- updated specs
- archive location
- test evidence
- CRG evidence
- merge/PR readiness
AIWK_EOF

cat > .claude/commands/spcrg-bugfix.md <<'AIWK_EOF'
# Spcrg Bugfix Workflow

Bug:

$ARGUMENTS

Use the lightweight bugfix workflow unless behavior/spec changes are discovered.

## Gate policy

A plain bugfix does **not** create an OpenSpec change, so the OpenSpec gate scripts are **not** run here.

However, as soon as the bug analysis reveals that expected behavior, public API, data model, or spec must change:

1. Stop bugfix workflow.
2. Run `/opsx:propose fix-{bug-name}`.
3. From that point treat it as a feature-style change:
   - `/spcrg-plan fix-{bug-name}`
   - `/spcrg-dev fix-{bug-name}`
   - `/spcrg-review fix-{bug-name}`
   - `/spcrg-archive fix-{bug-name}`
4. All feature-style gate scripts apply from that point.

## Debugging

Use:

superpowers:systematic-debugging

## CRG required for diagnosis

- get_minimal_context_tool
- semantic_search_nodes_tool
- query_graph_tool callers/callees/imports/tests_for
- get_impact_radius_tool

If root cause is unclear, also use:

- traverse_graph_tool
- get_affected_flows_tool
- get_review_context_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server.

## Then

1. Write regression test.
2. Use superpowers:test-driven-development.
3. Fix minimally.
4. Run CRG after fix:
   - detect_changes_tool
   - get_impact_radius_tool
   - query_graph_tool pattern="tests_for"

If expected behavior changes, stop and upgrade to:

/opsx:propose fix-{bug-name}
AIWK_EOF

cat > .claude/commands/spcrg-hotfix.md <<'AIWK_EOF'
# Spcrg Hotfix Workflow

Production issue:

$ARGUMENTS

Use hotfix workflow.

## Rules

- Minimal fix only.
- No refactor.
- No opportunistic cleanup.
- Must add regression test.
- Must produce rollback plan.

## OpenSpec hotfix record (optional)

If this hotfix needs to be tracked in OpenSpec, create:

- openspec/changes/hotfix-{issue-id}/proposal.md
- openspec/changes/hotfix-{issue-id}/tasks.md

When a hotfix OpenSpec record exists, the gate applies **before archive or release-readiness sign-off**:

```
scripts/check-openspec-gate.sh hotfix-{issue-id}
scripts/check-crg-evidence.sh hotfix-{issue-id}
```

If either script fails:

1. Do not mark the hotfix as ready to ship.
2. Do not run `/opsx:verify` or `/opsx:archive`.
3. Fix the missing artifacts/evidence, then re-run the scripts.

For hotfixes without an OpenSpec record, skip the OpenSpec gate but still produce CRG evidence in the PR description.

## Debugging

Use:

superpowers:systematic-debugging

## CRG fast diagnosis required

- get_minimal_context_tool
- semantic_search_nodes_tool
- query_graph_tool callers/callees/tests_for
- get_impact_radius_tool

If production user flow is affected:

- list_flows_tool
- get_flow_tool
- get_affected_flows_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server.

## After fix

- detect_changes_tool
- get_impact_radius_tool
- get_review_context_tool
- query_graph_tool pattern="tests_for"

Run critical tests and E2E if relevant.

Stop if blast radius exceeds hotfix scope.
AIWK_EOF

cat > .claude/commands/spcrg-refactor.md <<'AIWK_EOF'
# Spcrg Refactor Workflow

Refactor goal:

$ARGUMENTS

Use CRG + Superpowers refactor workflow.

## CRG refactor assessment

Required CRG tools:

- get_architecture_overview_tool
- list_communities_tool
- get_community_tool
- get_hub_nodes_tool
- get_bridge_nodes_tool
- find_large_functions_tool
- get_knowledge_gaps_tool
- get_surprising_connections_tool
- get_impact_radius_tool
- query_graph_tool callers/callees/tests_for
- refactor_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Use the actual tool names exposed by the CRG MCP server.

Use apply_refactor_tool only after:

- refactor_tool preview reviewed
- test strategy clear
- blast radius acceptable
- user approved

## Superpowers

Use superpowers:brainstorming to clarify:

- refactor goal
- behavior preservation
- scope boundary
- risk
- test strategy

If external behavior, public API, or architecture rules change, stop and upgrade to:

/opsx:propose {refactor-change-name}
AIWK_EOF

cat > .claude/commands/spcrg-audit.md <<'AIWK_EOF'
# Spcrg CRG Evidence Audit

Change ID:

$ARGUMENTS

## Resolve change-id if missing

If `$ARGUMENTS` is empty:

1. Run `scripts/detect-change-id.sh`.
2. If exactly one active change exists, report it and ask the user to confirm before using it.
3. If multiple active changes exist, list them and ask the user to pick one.
4. If none exist, tell the user there is nothing to audit and stop.

Do not proceed until a concrete change-id is chosen.

## Gate: at start of audit

Run:

```
scripts/check-openspec-gate.sh $ARGUMENTS
scripts/check-crg-evidence.sh $ARGUMENTS
```

Audit behavior is **report-only**:

1. If either script fails, include the failure in the audit report.
2. Do not auto-repair evidence unless the user explicitly asks.
3. Continue the remainder of the audit even if scripts fail, so the full gap list is produced in one pass.

## Audit scope

Check these files:

- openspec/changes/$ARGUMENTS/proposal.md
- openspec/changes/$ARGUMENTS/design.md
- openspec/changes/$ARGUMENTS/tasks.md
- openspec/changes/$ARGUMENTS/specs/**

### Required evidence

1. proposal.md has CRG Architecture Context.
2. design.md has CRG Impact Analysis.
3. tasks.md has CRG Planning Evidence.
4. Each implementation phase has CRG Pre-Phase Check.
5. Each implementation phase has CRG Post-Phase Check.
6. Final review includes CRG Final Impact Review.
7. Archive/verify includes CRG Archive Gate.

### Required tool names must appear where applicable

Baseline:

- get_minimal_context_tool
- semantic_search_nodes_tool
- query_graph_tool
- get_impact_radius_tool
- detect_changes_tool
- get_review_context_tool
- get_affected_flows_tool
- get_knowledge_gaps_tool

For complex changes also check:

- get_architecture_overview_tool
- list_communities_tool
- get_community_tool
- get_hub_nodes_tool
- get_bridge_nodes_tool
- get_surprising_connections_tool
- get_suggested_questions_tool

> Tool names may appear with or without the `_tool` suffix in Claude Code. Accept either form during audit, but note which form was recorded.

## Report

- missing evidence
- missing tools
- stale evidence
- gate script results
- whether next phase is allowed

If evidence is missing, do not continue to the next phase. Fix evidence first.
AIWK_EOF

cat > .claude/skills/project-development-workflow/SKILL.md <<'AIWK_EOF'
---
name: project-development-workflow
description: Use for all feature work, bugfixes, hotfixes, refactors, OpenSpec OPSX changes, CRG evidence checks, and Superpowers-driven development in this project.
---

# Project Development Workflow

Use OpenSpec OPSX, Superpowers, and CRG together.

## Responsibilities

- OpenSpec defines intended behavior.
- CRG defines code facts, dependencies, execution flows, architecture hotspots, and test coverage.
- Superpowers defines execution discipline.

## Core Rules

1. New features and significant changes start with `/spcrg-start`.
2. Do not implement until OpenSpec artifacts and CRG Evidence exist.
3. Use `superpowers:brainstorming` after OpenSpec proposal and CRG Context Pass.
4. Use `superpowers:writing-plans` before implementation.
5. Use `superpowers:subagent-driven-development` for implementation.
6. Use CRG Pre-Phase and Post-Phase checks around every implementation phase.
7. Run OpenSpec compliance review, CRG final impact review, and Superpowers review before archive.
8. Run `/opsx:verify` before `/opsx:archive` when available.

## Command Map

- `/spcrg-start <description>` — propose + CRG Context Pass + brainstorming (gate runs at the **end**, before asking for approval)
- `/spcrg-plan <change-id>` — rewrite tasks.md with TDD + CRG checks (gate runs **first**)
- `/spcrg-dev <change-id>` — subagent-driven TDD execution with CRG pre/post checks (gate runs **first**)
- `/spcrg-review <change-id>` — OpenSpec + CRG + Superpowers review (gate runs **first**)
- `/spcrg-archive <change-id>` — verification + CRG Archive Gate + /opsx:verify + /opsx:archive (gate runs **first**, and re-checks right before `/opsx:verify`)
- `/spcrg-bugfix <bug>` — lightweight systematic debugging + CRG diagnosis. No OpenSpec gate for plain bugfixes; upgrade to `/opsx:propose fix-...` if behavior changes, then feature-style gates apply.
- `/spcrg-hotfix <incident>` — minimal production fix + CRG fast diagnosis. If a hotfix OpenSpec record is created, gates apply before archive / release-readiness.
- `/spcrg-refactor <goal>` — CRG refactor assessment + Superpowers brainstorming
- `/spcrg-audit <change-id>` — CRG evidence completeness audit (gate runs but is **report-only**)

## Gate Script Matrix

| Command | When to run gate scripts | Must-run scripts | On failure |
|---|---|---|---|
| `/spcrg-start` | after propose + CRG + brainstorm + write-back | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not request approval; repair and re-run |
| `/spcrg-plan` | first step | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not run `superpowers:writing-plans` |
| `/spcrg-dev` | first step | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not run `superpowers:subagent-driven-development` |
| `/spcrg-review` | first step | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not enter final review |
| `/spcrg-archive` | first step, and re-check right before `/opsx:verify` | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not run `/opsx:verify` or `/opsx:archive` |
| `/spcrg-audit` | first step | `check-openspec-gate.sh`, `check-crg-evidence.sh` | report only; no auto-repair unless requested |
| `/spcrg-bugfix` | not required for plain bugfix | n/a | if upgraded to OpenSpec change, gates apply |
| `/spcrg-hotfix` | before archive/release sign-off, only if OpenSpec hotfix record exists | `check-openspec-gate.sh`, `check-crg-evidence.sh` | do not mark ready to ship |

## Missing change-id handling

If `$ARGUMENTS` is empty for `/spcrg-plan`, `/spcrg-dev`, `/spcrg-review`, `/spcrg-archive`, `/spcrg-audit`:

1. Run `scripts/detect-change-id.sh`.
2. One active change → confirm with the user before using it.
3. Multiple active changes → list them and ask the user to pick.
4. No active changes → instruct the user to run `/spcrg-start` first.

## CRG tool names

Tool names in Claude Code may appear with or without the `_tool` suffix. Use whatever name the CRG MCP server actually exposes, and record the exact tool names used in CRG Evidence so later audits can verify usage.

## Stop Conditions

Stop and report if:

- CRG is unavailable.
- CRG evidence is missing.
- OpenSpec and code disagree.
- Unexpected blast radius appears.
- Required tests cannot be found or run.
- E2E is required but unavailable.
- A subagent needs to exceed OpenSpec scope.
- A gate script keeps failing after a repair attempt.
AIWK_EOF

cat > scripts/check-crg-evidence.sh <<'AIWK_EOF'
#!/usr/bin/env bash
set -euo pipefail

change_id="${1:-}"

if [ -z "$change_id" ]; then
  echo "Usage: scripts/check-crg-evidence.sh <change-id>"
  exit 1
fi

base="openspec/changes/$change_id"

if [ ! -d "$base" ]; then
  echo "OpenSpec change not found: $base"
  exit 1
fi

required_files=(
  "$base/proposal.md"
  "$base/design.md"
  "$base/tasks.md"
)

for file in "${required_files[@]}"; do
  if [ ! -f "$file" ]; then
    echo "Missing file: $file"
    exit 1
  fi

  if ! grep -qi "CRG" "$file"; then
    echo "Missing CRG evidence in $file"
    exit 1
  fi
done

required_tools=(
  "get_minimal_context"
  "semantic_search_nodes"
  "query_graph"
  "get_impact_radius"
)

for tool in "${required_tools[@]}"; do
  if ! grep -R -q "$tool" "$base"; then
    echo "Missing required CRG tool evidence: $tool"
    exit 1
  fi
done

echo "CRG evidence baseline found for $change_id"
AIWK_EOF

cat > scripts/check-openspec-gate.sh <<'AIWK_EOF'
#!/usr/bin/env bash
set -euo pipefail

change_id="${1:-}"

if [ -z "$change_id" ]; then
  echo "Usage: scripts/check-openspec-gate.sh <change-id>"
  exit 1
fi

base="openspec/changes/$change_id"

if [ ! -d "$base" ]; then
  echo "OpenSpec change not found: $base"
  exit 1
fi

missing=0

for file in proposal.md design.md tasks.md; do
  if [ ! -f "$base/$file" ]; then
    echo "Missing $base/$file"
    missing=1
  fi
done

if [ ! -d "$base/specs" ]; then
  echo "Missing $base/specs"
  missing=1
fi

if [ "$missing" -ne 0 ]; then
  exit 1
fi

echo "OpenSpec gate passed for $change_id"
AIWK_EOF

cat > scripts/detect-change-id.sh <<'AIWK_EOF'
#!/usr/bin/env bash
set -euo pipefail

changes_dir="openspec/changes"

if [ ! -d "$changes_dir" ]; then
  echo "openspec/changes not found"
  exit 1
fi

find "$changes_dir" -maxdepth 1 -mindepth 1 -type d \
  ! -name archive \
  -exec basename {} \; | sort
AIWK_EOF

cat > scripts/verify-install.sh <<'AIWK_EOF'
#!/usr/bin/env bash
#
# verify-install.sh — acceptance checks for the AI Workflow Kit (spcrg prefix).
#
# Implements §14.1–14.3 from the implementation handbook:
#   1. All nine commands exist.
#   2. All three gate scripts exist and are executable.
#   3. Commands that need an embedded gate actually embed it.
#
# Exits non-zero on any failure and prints a summary.

set -euo pipefail

root="${1:-.}"
cd "$root"

fail=0
note() { printf "  %s\n" "$*"; }
ok()   { printf "  \033[32mok\033[0m  %s\n" "$*"; }
bad()  { printf "  \033[31mfail\033[0m %s\n" "$*"; fail=$((fail+1)); }

echo "[1/4] commands exist"
required_commands=(
  .claude/commands/spcrg-start.md
  .claude/commands/spcrg-plan.md
  .claude/commands/spcrg-dev.md
  .claude/commands/spcrg-review.md
  .claude/commands/spcrg-archive.md
  .claude/commands/spcrg-bugfix.md
  .claude/commands/spcrg-hotfix.md
  .claude/commands/spcrg-refactor.md
  .claude/commands/spcrg-audit.md
)
for f in "${required_commands[@]}"; do
  if [ -f "$f" ]; then ok "$f"; else bad "missing $f"; fi
done

echo ""
echo "[2/4] gate scripts exist and are executable"
required_scripts=(
  scripts/check-crg-evidence.sh
  scripts/check-openspec-gate.sh
  scripts/detect-change-id.sh
)
for f in "${required_scripts[@]}"; do
  if [ ! -f "$f" ]; then
    bad "missing $f"
  elif [ ! -x "$f" ]; then
    bad "$f is not executable (run: chmod +x $f)"
  else
    ok "$f"
  fi
done

echo ""
echo "[3/4] commands embed gate script calls"
gated_commands=(
  .claude/commands/spcrg-plan.md
  .claude/commands/spcrg-dev.md
  .claude/commands/spcrg-review.md
  .claude/commands/spcrg-archive.md
  .claude/commands/spcrg-audit.md
)
for f in "${gated_commands[@]}"; do
  if [ ! -f "$f" ]; then
    bad "$f missing (cannot check gate header)"
    continue
  fi
  if grep -q "check-openspec-gate.sh" "$f" && grep -q "check-crg-evidence.sh" "$f"; then
    ok "$f embeds both gate scripts"
  else
    bad "$f does not embed both gate scripts"
  fi
done

echo ""
echo "[4/4] spcrg-start.md runs gate after artifacts"
if [ -f .claude/commands/spcrg-start.md ]; then
  if grep -q "check-openspec-gate.sh" .claude/commands/spcrg-start.md \
     && grep -q "check-crg-evidence.sh" .claude/commands/spcrg-start.md; then
    ok ".claude/commands/spcrg-start.md embeds gate scripts at the end"
  else
    bad "spcrg-start.md must embed both gate scripts"
  fi
fi

echo ""
if [ "$fail" -eq 0 ]; then
  printf "\033[32mAll acceptance checks passed.\033[0m\n"
  exit 0
else
  printf "\033[31m%s acceptance check(s) failed.\033[0m\n" "$fail"
  exit 1
fi
AIWK_EOF

chmod +x scripts/check-crg-evidence.sh
chmod +x scripts/check-openspec-gate.sh
chmod +x scripts/detect-change-id.sh
chmod +x scripts/verify-install.sh

echo ""
echo "AI Workflow Kit installed."
echo ""
echo "Verifying installation..."
if scripts/verify-install.sh .; then
  echo ""
  echo "Next:"
  echo "  1. Append the Project AI Workflow Kit section to your CLAUDE.md"
  echo "  2. Ensure OpenSpec, Superpowers, and code-review-graph are set up"
  echo "  3. Try: /spcrg-start <description>"
else
  echo ""
  echo "Installation finished but acceptance checks failed — see output above."
  exit 1
fi
